text:
	dc.b "            "
	dc.b "            "
	dc.b "   QFLUSH   "
	dc.b " OFFERS YA  "
	dc.b "            "
	dc.b " QRASFATARI "
	dc.b "            "
	dc.b "DA ^K SPLIFF"
	dc.b "  ROLLED BY "
	dc.b "   FLEWWW   "
	dc.b " NQ GLAFOUK "
	dc.b "RELEASED FOR"
	dc.b "SHADOW PARTY"
	dc.b "        ][]\"
	dc.b "            "
	dc.b "  RULES OF  "
	dc.b "RASFATARISM_"
	dc.b "RACE DA BEAM"
	dc.b "SMOKE DA TIA"
	dc.b "DRINK DA ROM"
	dc.b "FUCK DA BYTE"
	dc.b " SHARE CODE "
	dc.b "NQ STAY IRIE"
	dc.b "            "
	dc.b "JAY BLESSING"
	dc.b "NQ BIG UP TO"
	dc.b "      ALTAIR"
	dc.b "    BOCK    "
	dc.b "CLUSTER     "
	dc.b "       COINE"
	dc.b "COOKIE CREW "
	dc.b "   DELICIOUS"
	dc.b "   AMIGANS  "
	dc.b "DENTIFRICE  "
	dc.b "         DMA"
	dc.b "DUNE        "
	dc.b 0,"           "
	dc.b "            "
