text:
        dc.b "            "
        dc.b "            "
        dc.b "   FLUSH    "
        dc.b "  KNITTED   "
        dc.b " THIS MERRY "
        dc.b " ATARI VCS  "
        dc.b "  \K INTRO  "
        dc.b "  BECAUSE   "
        dc.b " SOMETIMES  "
        dc.b "    LIFE    "
        dc.b "JUST TASTES "
        dc.b "LIKE A CANDY"
        dc.b "            "
        dc.b "  WELCOME   "
        dc.b "  ON BOARD  "
        dc.b "TO CLOU FOR "
        dc.b "CONTRIBUTING"
        dc.b "  TO THIS   "
        dc.b "TRIBUTE FOR "
        dc.b " OUR MISSED "
        dc.b "NOICY SHADOW"
        dc.b "            "
        dc.b "CREDITS FOR "
        dc.b "MSX[ GLAFOUK"
        dc.b "GFX[ CLOU   "
        dc.b "CDX[ FLEWWW "
        dc.b "            "
        dc.b "N GREETZ TO "
        dc.b "ALTAIR      "
        dc.b "       BOCK "
        dc.b "BOOZ DESIGN "
        dc.b " COOKIE CREW"
        dc.b "DENTIFRICE  "
        dc.b "     GENESIS"
        dc.b "     PROJECT"
        dc.b "GOBLINISH   "
        dc.b "HOOY PROGRAM"
        dc.b "   JAC      "
        dc.b "LABORATOIRE "
        dc.b "PROUT       "
        dc.b "MYSTIC BYTES"
        dc.b "     NOICE  "
        dc.b "PLANET JAZZ "
        dc.b "RBBS        "
        dc.b "  SECTOR ONE"
        dc.b "UP ROUGH    "
        dc.b "VITAL MOTION"
        dc.b "       X MEN"
        dc.b 0,"           "
	dc.b "            "
